av_id: west2844
name: Western Micronesian
glottocode: west2844
family: Austronesian
macroarea: ''
sources:
  transcription: mcd
  cognates: mcd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.5163
  cognates_score: 0.7
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=mcd (0.52); cognates=mcd (0.70)'
