av_id: yamb1257
name: Yamben
glottocode: yamb1257
family: Nuclear Trans New Guinea
macroarea: Papunesia
sources:
  transcription: transnewguineaorg
  cognates: transnewguineaorg
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.7235
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=transnewguineaorg (0.72)'
