av_id: map-selayar
name: Selayar
glottocode: sela1260
family: Austronesian
macroarea: Papunesia
sources:
  transcription: acd
  cognates: acd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.07
  cognates_score: 0.6364
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=acd (0.07); cognates=acd (0.64)'
