av_id: bwai1242
name: Bwaidoka
glottocode: bwai1242
family: Austronesian
macroarea: Papunesia
sources:
  transcription: acd
  cognates: acd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.0308
  cognates_score: 0.5911
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=acd (0.03); cognates=acd (0.59)'
