av_id: mosk1236
name: Moskona
glottocode: mosk1236
family: East Bird's Head
macroarea: Papunesia
sources:
  transcription: johanssonsoundsymbolic
  cognates: johanssonsoundsymbolic
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.8799
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=johanssonsoundsymbolic (0.88)'
