av_id: map-lamenu-lewo
name: Lamenu-Lewo
glottocode: lame1259
family: Austronesian
macroarea: ''
sources:
  transcription: abvd
  cognates: abvd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
  profile: false
scoring:
  forms_score: 0.5
  cognates_score: 0.6454
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=abvd (0.50); cognates=abvd (0.65)'
