av_id: nua-au
name: Au
glottocode: auuu1241
family: Nuclear Torricelli
macroarea: Papunesia
sources:
  transcription: transnewguineaorg
  cognates: transnewguineaorg
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.7673
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=transnewguineaorg (0.77)'
