av_id: map-bisayan
name: Bisayan
glottocode: bisa1268
family: Austronesian
macroarea: ''
sources:
  transcription: abvd
  cognates: abvd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.3943
  cognates_score: 0.6076
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=abvd (0.39); cognates=abvd (0.61)'
