av_id: hmx-northern-huishui-hmong
name: Northern Huishui Hmong
glottocode: nort2749
family: Hmong-Mien
macroarea: Eurasia
sources:
  transcription: chenhmongmien
  cognates: chenhmongmien
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.7339
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=chenhmongmien (0.73)'
