av_id: raoj1238
name: Raojin
glottocode: raoj1238
family: Austroasiatic
macroarea: Eurasia
sources:
  transcription: deepadungpalaung
  cognates: deepadungpalaung
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.7929
  cognates_score: 0.7
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=deepadungpalaung (0.79); cognates=deepadungpalaung (0.70)'
