av_id: kala1391
name: Kalabakan
glottocode: kala1391
family: Austronesian
macroarea: Papunesia
sources:
  transcription: acd
  cognates: acd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.0588
  cognates_score: 0.35
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=acd (0.06); cognates=acd (0.35)'
