av_id: nort2638
name: Swedish VL
glottocode: nort2638
family: ''
macroarea: ''
sources:
  transcription: dyenindoeuropean
  cognates: dyenindoeuropean
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.443
  cognates_score: 0.6021
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=dyenindoeuropean (0.44); cognates=dyenindoeuropean (0.60)'
