av_id: neta1235
name: North Midlands Tasmanian
glottocode: neta1235
family: North-Eastern Tasmanian
macroarea: Australia
sources:
  transcription: bowerntasmanian
  cognates: bowerntasmanian
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.4259
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=bowerntasmanian (0.43)'
