av_id: hmon1336
name: Hmong-Mien
glottocode: hmon1336
family: Hmong-Mien
macroarea: ''
sources:
  transcription: abvd
  cognates: abvd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.3907
  cognates_score: 0.0196
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=abvd (0.39); cognates=abvd (0.02)'
