av_id: ani-warkay-bipim
name: Warkay-Bipim
glottocode: wark1247
family: Anim
macroarea: Papunesia
sources:
  transcription: transnewguineaorg
  cognates: transnewguineaorg
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.8103
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=transnewguineaorg (0.81)'
