av_id: cent2060
name: Central Pacific linkage
glottocode: cent2060
family: Austronesian
macroarea: ''
sources:
  transcription: abvd
  cognates: abvd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.464
  cognates_score: 0.6886
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=abvd (0.46); cognates=abvd (0.69)'
