av_id: ping1243
name: Pingelapese
glottocode: ping1243
family: Austronesian
macroarea: Papunesia
sources:
  transcription: mcd
  cognates: mcd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.5339
  cognates_score: 0.6555
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=mcd (0.53); cognates=mcd (0.66)'
