av_id: ine-chima-nishey
name: Chima-Nishey
glottocode: chim1297
family: Indo-European
macroarea: Eurasia
sources:
  transcription: iecor
  cognates: iecor
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.8493
  cognates_score: 0.7
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=iecor (0.85); cognates=iecor (0.70)'
