av_id: nucl1729
name: Nuclear Tamang
glottocode: nucl1729
family: Sino-Tibetan
macroarea: ''
sources:
  transcription: peirosst
  cognates: peirosst
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.6437
  cognates_score: 0.7
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=peirosst (0.64); cognates=peirosst (0.70)'
