av_id: sout3229
name: South Halmahera-West New Guinea
glottocode: sout3229
family: Austronesian
macroarea: ''
sources:
  transcription: acd
  cognates: acd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.0488
  cognates_score: 0.0049
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=acd (0.05); cognates=acd (0.00)'
