av_id: ipai1240
name: Ipai
glottocode: ipai1240
family: Cochimi-Yuman
macroarea: North America
sources:
  transcription: wheelerutoaztecan
  cognates: wheelerutoaztecan
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.755
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=wheelerutoaztecan (0.75)'
