av_id: afa-jibbali
name: Jibbali
glottocode: sheh1240
family: Afro-Asiatic
macroarea: Eurasia
sources:
  transcription: kogansemitic
  cognates: kogansemitic
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
  profile: false
scoring:
  forms_score: 0.679
  cognates_score: 0.7
  tier: silver
pinned: false
registered_on: '2026-05-20'
notes: 'switched to kogansemitic as single Semitic source'
