av_id: afa-tarifiyt-beni-iznasen-eastern-middle-atlas-berber
name: Tarifiyt-Beni-Iznasen-Eastern Middle Atlas Berber
glottocode: tari1263
family: Afro-Asiatic
macroarea: Africa
sources:
  transcription: wold
  cognates: wold
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
  profile: false
scoring:
  forms_score: 0.9871
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=wold (0.99)'
