av_id: atl-kyak
name: Kyak
glottocode: kyak1243
family: Atlantic-Congo
macroarea: Africa
sources:
  transcription: othanieljen
  cognates: othanieljen
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.7366
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=othanieljen (0.74)'
