av_id: map-mapia
name: Mapia
glottocode: mapi1250
family: Austronesian
macroarea: Papunesia
sources:
  transcription: mcd
  cognates: mcd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
  profile: false
scoring:
  forms_score: 0.4873
  cognates_score: 0.7
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=mcd (0.49); cognates=mcd (0.70)'
