av_id: suki1245
name: Suki
glottocode: suki1245
family: Suki-Gogodala
macroarea: Papunesia
sources:
  transcription: transnewguineaorg
  cognates: transnewguineaorg
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.8053
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=transnewguineaorg (0.81)'
