av_id: afa-argobba
name: Argobba
glottocode: argo1244
family: Afro-Asiatic
macroarea: Africa
sources:
  transcription: kogansemitic
  cognates: kogansemitic
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
  profile: false
scoring:
  forms_score: 0.6121
  cognates_score: 0.7
  tier: silver
pinned: false
registered_on: '2026-05-20'
notes: 'switched to kogansemitic as single Semitic source'
