av_id: sit-phuza
name: Phuza
glottocode: phuz1235
family: Sino-Tibetan
macroarea: Eurasia
sources:
  transcription: yangyi
  cognates: yangyi
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
  profile: false
scoring:
  forms_score: 0.7353
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=yangyi (0.74)'
