av_id: toka1244
name: Tokano
glottocode: toka1244
family: Nuclear Trans New Guinea
macroarea: Papunesia
sources:
  transcription: transnewguineaorg
  cognates: transnewguineaorg
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.8511
  cognates_score: 0.0
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=transnewguineaorg (0.85)'
