av_id: und-armenian-mod
name: Armenian Mod
glottocode: east2283
family: ''
macroarea: ''
sources:
  transcription: dyenindoeuropean
  cognates: dyenindoeuropean
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
  profile: false
scoring:
  forms_score: 0.4396
  cognates_score: 0.5621
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=dyenindoeuropean (0.44); cognates=dyenindoeuropean (0.56)'
