av_id: urj-south-estonian
name: South Estonian
glottocode: sout2679
family: Uralic
macroarea: Eurasia
sources:
  transcription: uralex
  cognates: uralex
  source_glottocode: voro1241
  source_language_id: uralex_estonian_south
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
  profile: false
scoring:
  forms_score: 0.7475
  cognates_score: 0.7
  tier: silver
pinned: false
registered_on: '2026-05-20'
notes: 'switched to uralex via source_glottocode voro1241 (estonian_south)'
