av_id: nuc-asmat-kamoro
name: Asmat-Kamoro
glottocode: asma1256
family: Nuclear Trans New Guinea
macroarea: ''
sources:
  transcription: abvd
  cognates: abvd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.3046
  cognates_score: 0.0
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=abvd (0.30)'
