av_id: map-batanic
name: Batanic
glottocode: bata1315
family: Austronesian
macroarea: ''
sources:
  transcription: abvd
  cognates: abvd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.4407
  cognates_score: 0.5205
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=abvd (0.44); cognates=abvd (0.52)'
