av_id: map-chuukic-ponapeic
name: Chuukic-Ponapeic
glottocode: pona1247
family: Austronesian
macroarea: ''
sources:
  transcription: mcd
  cognates: mcd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
  profile: false
scoring:
  forms_score: 0.428
  cognates_score: 0.1028
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=mcd (0.43); cognates=mcd (0.10)'
