av_id: mayo1262
name: Mayoyao Ifugao
glottocode: mayo1262
family: Austronesian
macroarea: Papunesia
sources:
  transcription: acd
  cognates: acd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.1
  cognates_score: 0.6393
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=acd (0.10); cognates=acd (0.64)'
