av_id: muss1246
name: Mussau-Emira
glottocode: muss1246
family: Austronesian
macroarea: Papunesia
sources:
  transcription: acd
  cognates: acd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.0414
  cognates_score: 0.6918
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=acd (0.04); cognates=acd (0.69)'
