av_id: cent2080
name: Central Luzon
glottocode: cent2080
family: Austronesian
macroarea: ''
sources:
  transcription: abvd
  cognates: abvd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.3215
  cognates_score: 0.3286
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=abvd (0.32); cognates=abvd (0.33)'
