av_id: map-miri-malaysia
name: Miri (Malaysia)
glottocode: miri1269
family: Austronesian
macroarea: Papunesia
sources:
  transcription: acd
  cognates: acd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.0856
  cognates_score: 0.6663
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=acd (0.09); cognates=acd (0.67)'
