av_id: boho1237
name: Boholano
glottocode: boho1237
family: Austronesian
macroarea: Papunesia
sources:
  transcription: acd
  cognates: acd
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
scoring:
  forms_score: 0.0644
  cognates_score: 0.56
  tier: copper
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=acd (0.06); cognates=acd (0.56)'
