av_id: map-bidayuh-southern-land-dayak
name: Bidayuh-Southern Land Dayak
glottocode: bida1239
family: Austronesian
macroarea: ''
sources:
  transcription: smithborneo
  cognates: smithborneo
extensions:
  transcriptions: false
  forms: false
  cognates: false
  concept_map: false
  profile: false
scoring:
  forms_score: 0.522
  cognates_score: 0.7
  tier: bronze
pinned: false
registered_on: '2026-05-20'
notes: 'auto: forms=smithborneo (0.52); cognates=smithborneo (0.70)'
